trigger:
- main

pool:
  name: build-env1

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(afed30c6-9cdc-4705-ac71-e9a6d1d52d8a)'
    KeyVaultName: 'azurekeyvaultdev01'
    SecretsFilter: '*'
    RunAsPreJob: false

- script: |
    echo "Secret Value: $(version)"
    # Use the secret in your script or tasks here
  env:
    mySecret: $(mySecret)
