trigger:
- main

pool:
  name: build-env

variables:
- group: shared-variables

jobs:
- job: UserDefinedVariables
  steps:
  - script: |
      echo "NGINX version: $(nginx_version)"
      echo "Deploy environment: $(deploy_env)"
      echo "Database : $(dbpassword)"
    displayName: 'Utilizing Variables from Variable Group'  