trigger:
- main

pool:
  name: build-env


variables:
  nginx_version: '2.4.8'
  deploy: 'dev'

jobs:
- job: UserDefinedVariables
  steps:
  - script: |
      echo "nginx version : $(nginx_version)"
      echo "deploying to : $(deploy)"
    displayName: 'utilizing variables'